[package]
name = "wry-example"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "wry"
path = "wry.rs"

[dependencies]
drag = { path = "../../crates/drag" }
tao = "0.23"
wry = { git = "https://github.com/tauri-apps/wry.git", branch = "dev" }
