[package]
name = "tauri-example"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "tauri"
path = "tauri.rs"

[build-dependencies]
tauri-build = "1"

[dependencies]
tauri = { version = "1", features = [ "path-all"] }
tauri-plugin-drag = { path = "../../crates/tauri-plugin/" }
