[package]
name = "tauri-app"
version = "0.0.0"
publish = false
edition = "2021"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri = { workspace = true, features = [] }
tauri-plugin-drag.workspace = true
